<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname( __DIR__, 1 );
$baseDir   = dirname( $vendorDir );

return array(
	'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
);
